name: Economy
version: '${version}'
main: dev.ahmet.economy.Economy
api-version: '1.20'
authors: [169ahmet]
description: Plugin by 169ahmet
commands:
  pay:
  payall:
  paytoggle:
  coins:
  balance:
    aliases:
      - money
      - bal